Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.network "private_network", ip: "192.168.50.2"
  config.vm.hostname = "master"

  # config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.provision "shell", path: "setup.sh"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    v.memory = 2048
    v.cpus = 2
  end
end